// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.SuberSirAntsABot2.autonomousroutines;

import org.usfirst.frc3244.SuperSirAntsABot2.Constants;
import org.usfirst.frc3244.SuperSirAntsABot2.Robot;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.ConditionalCommand;


/**
 *
 */
public class Auto_31_93_0_Conditional_SecondPlate extends ConditionalCommand {

    public Auto_31_93_0_Conditional_SecondPlate() {
      super(new Auto_31_93_1_Second_Cube_To_Switch(), new Finnished());
    }

    
    @Override
    protected boolean condition(){
    	Integer approachChoice = (Integer) Robot.multiCubeChooser.getSelected();
    	DriverStation.reportError("RUNING: Auto_31_93_0_Conditional_SecondPlate", false);
    	
    	if(approachChoice != null) {
    		if(approachChoice == 1){
    		DriverStation.reportError("Second Cube to Switch", false);
    			return true;
    		}else if(approachChoice == 2){
    			DriverStation.reportError("Second Cube Finnished", false);
    			return false;
    		}else {
    			return true;
    		}
        }else {
        	DriverStation.reportError("multiCubeChooser Null", false);
        	return true;
        }
    }
}
