// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.SuberSirAntsABot2.autonomousroutines;

import org.usfirst.frc3244.SuperSirAntsABot2.Constants;
import org.usfirst.frc3244.SuperSirAntsABot2.Robot;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.ConditionalCommand;


/**
 *
 */
public class Auto_13_2_Conditional_IsScale_L_R extends ConditionalCommand {

    public Auto_13_2_Conditional_IsScale_L_R() {
      super(new Auto_12_3_0_Conditional_Approach_Left_Scale(), new Auto_13_4_Deliver_Right_Scale_From_Left_00_To_Plate());
    }

    @Override
    protected boolean condition(){
    	String s = Robot.gameData;
    	DriverStation.reportError("RUNING: Auto_13_2_Conditional_IsScale_L_R()", false);
    	if(s.length() > 0){
    		if(s.charAt(Constants.kGameDataOurScaleChar) == 'L'){
    			DriverStation.reportError("Scale IS L", false);
    			return true;
    		}else{
    			DriverStation.reportError("Scale NOT L", false);
    			return false;
    		}
        }else {
        	DriverStation.reportError("Game Data EMPTY", false);
        	return false;
        }
    }
}
