// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.SuberSirAntsABot2.autonomousroutines;

import org.usfirst.frc3244.SuperSirAntsABot2.Constants;
import org.usfirst.frc3244.SuperSirAntsABot2.Robot;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.ConditionalCommand;


/**
 *
 */
public class Auto_12_5_0_Conditional_WhatPlate extends ConditionalCommand {

    public Auto_12_5_0_Conditional_WhatPlate() {
    	super(new Auto_12_5_1_Left_Cube_2_to_Scale(), new Auto_12_5_2_Conditional_Cube_2_IsSwitch_L());
    }

    @Override
    protected boolean condition(){
    	Integer multiCubeChoice = (Integer) Robot.multiCubeChooser.getSelected();
    	DriverStation.reportError("RUNING: Auto_12_5_0_Conditional_WhatPlate()", false);
    	
    	if(multiCubeChoice != null) {
    		if(multiCubeChoice == 1){
    		DriverStation.reportError("Same Plate", false);
    			return true;
    		}else{
    			DriverStation.reportError("Other Plate", false);
    			return false;
    		}
        }else {
        	DriverStation.reportError("multiCubeChooser Null Same Plate", false);
        	return true;
        }
    }
}
