// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.SuberSirAntsABot2.autonomousroutines;

import org.usfirst.frc3244.SuperSirAntsABot2.Constants;
import org.usfirst.frc3244.SuperSirAntsABot2.Robot;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.ConditionalCommand;


/**
 *
 */
public class Auto_36_2_Conditional_IsScale_R extends ConditionalCommand {

    public Auto_36_2_Conditional_IsScale_R() {
      super(new Auto_32_3_0_Conditional_Approach_Right_Scale(), new Auto_36_3_Conditional_IsSwitch_R());
    }

    
    @Override
    protected boolean condition(){
    	String s = Robot.gameData;
    	String com = this.getName();
    	DriverStation.reportError("RUNING: Auto_36_2_Conditional_IsScale_R()", false);
    	if(s.length() > 0){
    		if(s.charAt(Constants.kGameDataOurScaleChar) == 'R'){
    			DriverStation.reportError("Scale IS R", false);
    			return true;
    		}else{
    			DriverStation.reportError("Scale NOT R", false);
    			return false;
    		}
        }else {
        	DriverStation.reportError("Game Data EMPTY", false);
        	return false;
        }
    }
}
