// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.SuberSirAntsABot2.autonomousroutines;

import org.usfirst.frc3244.SuperSirAntsABot2.Constants;
import org.usfirst.frc3244.SuperSirAntsABot2.Robot;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.ConditionalCommand;


/**
 *
 */
public class Auto_11_2_Conditional_IsSwitch_L extends ConditionalCommand {

    public Auto_11_2_Conditional_IsSwitch_L() {
      super(new Auto_11_3_Deliver_Left_Switch(), new Auto_12_1_Start_Left_Deliver_IF_Lscale());
    }

    
    @Override
    protected boolean condition(){
    	String s = Robot.gameData;
    	String com = this.getName();
    	DriverStation.reportError("RUNING: Auto_11_2_Conditional_IsSwitch_L()", false);
    	if(s.length() > 0){
    		if(s.charAt(Constants.kGameDataOurSwitchChar) == 'L'){
    			DriverStation.reportError("Switch IS L", false);
    			return true;
    		}else{
    			DriverStation.reportError("Switch NOT L", false);
    			return false;
    		}
        }else {
        	DriverStation.reportError("Game Data EMPTY", false);
        	return false;
        }
    }
}
